### ISSUE TITLE
심화 주차 개인과제 피드백 - 정영훈 튜터

### ISSUE THREAD

**Issue by jyh7a** [soobeen0301/recruitment-site-2#9]
git readme, commit 굉장히 잘 작성해 주셨습니다. 
prisma로 migration도 잘 사용하고 있습니다. 

아래는 프로젝트 피드백입니다.

---

### 1. 이력서 목록 조회 API 수정 - repository 
https://github.com/soobeen0301/recruitment-site-2/blob/37afaf4e094e35d23c6816b4b4641eacf0cb6259/src/repositories/resumes.repository.js#L19-L38
이력서 목록 조회 readMany메서드 잘 작성 하였습니다. 
다만 repository에서는 db와 통신하는 로직을 위주로 작성하고 
service에서 정렬, 롤에 따른 where조건문 작성 등의 비지니스 로직을 처리하는것이 좋습니다.

현재 정렬, role condition 부분을 service 레이어의 readMany로 옮겨주세요.

<br/>

---

<br/>

### 2. 이력서 로그 목록 조회 API 수정 - repository 
https://github.com/soobeen0301/recruitment-site-2/blob/37afaf4e094e35d23c6816b4b4641eacf0cb6259/src/repositories/resumes.repository.js#L136-L144
readLog도 잘 작성 하였습니다. 
orderBy에서 내림차순 정렬만 고정적으로 하지말고 
추가 요구사항이나 변경에 유연하게 대처하기 위해서는 sortOrder라는 매개 변수를 통해서 내림차순 오름차순을 구분하게 코드를 작성하면 좋습니다.

예)
```javascript
readLog = async (id, sortOrder = 'desc') => {
    let data = await this.prisma.resumeLog.findMany({
      where: { resumeId: +id },
      orderBy: { createdAt: sortOrder },
      include: {
        recruiter: true,
      },
    });
```

<br/>

---

<br/>

### 3. 에러 및 예외 처리 
에러및 예외 처리쪽이 어려웠다고 하였는데 에러/예외 처리가 잘 되어 있습니다. 

가장 중요한 부분은 컨트롤러에서 try/catch를 사용하는것 입니다. 
service, repository에서 에러가 나더라도 controller에서 try/catch 구문으로 에러를 처리하기 때문에 next를 활용하여 에러 미들웨어에서 에러를 처리할 수 있습니다. 

예외처리도 서비스 로직에서 아래와 같은 로직으로 잘 처리 하였습니다.
` if (isExistUser) {
      throw new HttpError.Conflict(MESSAGES.USER.COMMON.EMAIL.DUPLICATED);
    }`

예외처리가 잘 되는지 궁금하시면 controller에서 try/catch 구문을 모두 빼고 테스트해보고 다시 모두 작성 후 테스트 해본다면 try/catch 구문을 모두 작성한 후 api 테스트에서는 모든 상황에 적절한 응답을 받는것을 알 수 있습니다.

<br/>

---

<br/>

### 4. 나머지 기능 구현 
이제 나머지 유닛테스트 기능을 구현해 보세요. 
심화 해설 영상을 먼저 보고 repository부터 차례대로 유닛테스트 진행해 주세요.

**Comment by soobeen0301** [comment]
코드 리팩토링 완료
